name: my flask-app ci
on:
  push:
     branches: [main]
     path:
       - 'project-1/**' 
  pull_request:
     branches: [main]
     path:
       - 'project-1/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v4
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install dependencies
      run: |
        pip install flask pytest
        if [ -f requirements.txt ]; then pip install -r requirments.txt; fi
    - name: run  test
      run: pytest test_app.py
