name: my node app
on:
  push:
    branches: [main]
    paths:
      - 'node-app-pipeline/**'
  pull_request: 
    branches: [main]
    paths:
      - 'node-app-pipeline/**'
jobs:
  runs-on: ubuntu:latest
  build:
    steps:
    - name: check the code
      uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v4
      with:
       node-version: '20'
    - name: install dependencies
      run:  npm install
    - name: start the project
      run: npm start
    - name: test  the project
      run:  npm test && echo " app is running"


           
